[package]
name = "Esercizio2_4"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
[lib]
name = "Esercizio2_4"
path = "src/lib/lib.rs"

[[test]]
name = "Esercizio2_4"
path = "tests/test.rs"

